# ==========================================================
# Spring Boot Server 配置
# ==========================================================

server:

  # Spring Boot HTTP 服务端口。
  #
  # Vue 开发环境一般使用 5173，
  # Java 后台使用 8080。
  port: 8080


spring:

  application:

    name: SOP-Server

onnx:
  # YOLO12 ONNX 模型路径
  model-path: Server/models/yolo12s.onnx
  # 是否启用 GPU (CUDA) 加速
  gpu:
    enabled: true
    device-id: 0
  # YOLO 输入图片尺寸
  input-size: 640
  # 置信度阈值
  conf-threshold: 0.25
  # NMS IoU 阈值
  iou-threshold: 0.45