# ==========================================================
# Spring Boot Server 配置
# ==========================================================

server:

  # Spring Boot HTTP 服务端口。
  #
  # Vue 开发环境一般使用 5173，
  # Java 后台使用 8080。
  port: 8080


spring:

  application:

    # 当前 Spring Boot 应用名称。
    name: SOP-Server